# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Gemini Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Gemini 3.5 Flash
    provider: gemini
    model: gemini-3.5-flash
    apiBase: http://127.0.0.1:8045/v1beta2/models
    apiKey: sk-f72fcdb1b9334c0ebf61d0ac4234f931
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
      - image_input
  - name: Gemini 3.6 Flash (High)
    provider: openai
    model: gemini-3.6-flash-high
    apiBase: http://127.0.0.1:8045/v1/
    apiKey: sk-f72fcdb1b9334c0ebf61d0ac4234f931
    roles:
      - apply
      - autocomplete
      - chat
      - edit
  - name: Claude Opus 4.6 (Thinking)
    provider: anthropic
    model: claude-opus-4-6-thinking
    apiBase: http://127.0.0.1:8045/v1
    apiKey: sk-f72fcdb1b9334c0ebf61d0ac4234f931
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    defaultCompletionOptions:
      contextLength: 200000
      maxTokens: 64000
    capabilities:
      - tool_use
      - image_input
  - name: Gemini 3.1 Pro
    provider: openai
    model: gemini-3.1-pro
    apiBase: http://127.0.0.1:8045/v1
    apiKey: sk-f72fcdb1b9334c0ebf61d0ac4234f931
    roles:
      - chat
      - edit
      - apply
      - autocomplete
